name: 'Create GitHub Pull Reaquest Action'
description: 'Creates a Pull Request for GitHub.'
author: 'Kenji Saito <ken-yo@mbr.nifty.com>'
branding:
  icon: 'terminal'
  color: 'yellow'
inputs:
  head_branch:
    description: (head) branch name
    required: true
  base_branch:
    description: target(base) branch name to merge
    default: main
  title:
    description: title for pull request
    default: Created by GitHub Action
  body:
    description: body text for pull request
    default: ''
  github_token:
    required: true
  owner:
    description: owner
    required: true
  repository:
    description: target repository
    required: true
outputs:
  result:
    description: A data object include the REST API response for creating a Pull Request.
runs:
  using: 'node24'
  main: 'dist/index.js'
