autoInstallPeers: true

legacyPeerDeps: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - pnpm

onlyBuiltDependencies:
  - esbuild

overrides:
  minimatch@<10.2.1: '>=10.2.1'

strictPeerDependencies: false
