packages:
  - .

allowBuilds:
  esbuild: false
autoInstallPeers: true

legacyPeerDeps: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - pnpm

overrides:
  brace-expansion@<1.1.13: '>=1.1.13'

strictPeerDependencies: false
