onlyBuiltDependencies:
  - esbuild

autoInstallPeers: true
legacyPeerDeps: true
strictPeerDependencies: false

# one day
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
 - pnpm

overrides:
  '@eslint/js@=9.39.0': "^9.39.1"
  'eslint@=9.39.0': "^9.39.1"
